* LintCode题解
  [[https://medium.com/always-be-coding/abc-always-be-coding-d5f8051afce2#.ixczkwou8][Always be coding!]]

  语言为C++11.

  所有代码均通过Lintcode在线检测, 同时也考虑了诸如内存泄露等产品级需求, 命名规范参考了Google C++命名,许多代码中注释的部分比如List/Tree的定义, 在源码中都uncomment掉了, 为的是本地调试需要,所以在进行在线检测时请把相关定义删掉以免造成在线编译不通过. +2016年11月02日完成lintcode目前所有题目(289题)+ . +2017年01月13日完成lintcode当前所有题目(294题).+  +2017年02月18日完成当前所有题目（295题）+ 增加了许多收费题目，所以之后应该不会跟了。

** 文件结构:
    举例来说明: 一个lintcode题目的url为: http://www.lintcode.com/zh-cn/problem/word-search-ii/ 则对应的文件名为 =./src/word-search-ii.cc=,在该文件中第一行的内容即为此URL的注释(此行内容是根据文件名再生成自动添加上)如果你是在Emacs中编辑此文件则可以在URL上M-x browse-url来打开这个链接, 因此对于题目的说明不会在文件中重复, 当然缺点就是你得有网络. 或者你可以在有网络的情况下根据这里的文件名写一个shell用wget全部download下来, 这样就可以躲到深山老林里刷这些题目了.

  #+BEGIN_QUOTE
  清明到来，我就38岁了，日暮乡关之感如针锥心

  薄雾从村头飘来，坐在橘园里，一些病果尚在枝头

  蒲公英又一次开出黄色的花，如一年一发的寂寞


  能够思念的人越来越少。我渐渐原谅了人世的凉薄

  如果回到过去，我确定会把爱过的人再爱一遍

  把疼痛过的再疼一遍

  但是我多么希望没有病痛的日子，一年或者一星期

  在春天的风里跳舞，踮起脚旋转

  他能看见也好，看不见也罢


  我只有一个愿望：生命静好，余生平安

  在春天的列车上有人为我让座

  不是因为我摇晃的身体

  -- 《人到中年》 余秀华
  #+END_QUOTE
